config/routes.rb
Rails.application.routes.draw do
   root to: "ajaxtests#index"

  resources :ajaxtests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ajaxtest.rb
class Ajaxtest < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ajaxtests_controller.rb
class AjaxtestsController < ApplicationController
  before_action :set_ajaxtest, only: %i[ show edit update destroy ]

  # GET /ajaxtests or /ajaxtests.json
  def index
    @ajaxtests = Ajaxtest.all
  end

  # GET /ajaxtests/1 or /ajaxtests/1.json
  def show
  end

  # GET /ajaxtests/new
  def new
    @ajaxtest = Ajaxtest.new
  end

  # GET /ajaxtests/1/edit
  def edit
  end

  # POST /ajaxtests or /ajaxtests.json
  def create
    @ajaxtest = Ajaxtest.new(ajaxtest_params)

    respond_to do |format|
      if @ajaxtest.save
        format.html { redirect_to ajaxtest_url(@ajaxtest), notice: "Ajaxtest was successfully created." }
        format.json { render :show, status: :created, location: @ajaxtest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ajaxtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ajaxtests/1 or /ajaxtests/1.json
  def update
    respond_to do |format|
      if @ajaxtest.update(ajaxtest_params)
        format.html { redirect_to ajaxtest_url(@ajaxtest), notice: "Ajaxtest was successfully updated." }
        format.json { render :show, status: :ok, location: @ajaxtest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ajaxtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ajaxtests/1 or /ajaxtests/1.json
  def destroy
    @ajaxtest.destroy

    respond_to do |format|
      format.html { redirect_to ajaxtests_url, notice: "Ajaxtest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ajaxtest
      @ajaxtest = Ajaxtest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ajaxtest_params
      params.require(:ajaxtest).permit(:name, :mobile)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/ajaxtests_helper.rb
module AjaxtestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ajaxtests/_form.html.erb
<%= form_with(model: ajaxtest) do |form| %>
  <% if ajaxtest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ajaxtest.errors.count, "error") %> prohibited this ajaxtest from being saved:</h2>

      <ul>
        <% ajaxtest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.number_field :mobile %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ajaxtests/edit.html.erb
<h1>Editing Ajaxtest</h1>

<%= render 'form', ajaxtest: @ajaxtest %>

<%= link_to 'Show', @ajaxtest %> |
<%= link_to 'Back', ajaxtests_path %>

app/views/ajaxtests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ajaxtests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ajaxtests.each do |ajaxtest| %>
      <tr>
        <td><%= ajaxtest.name %></td>
        <td><%= ajaxtest.mobile %></td>
        <td><%= link_to 'Show', ajaxtest %></td>
        <td><%= link_to 'Edit', edit_ajaxtest_path(ajaxtest) %></td>
        <td><%= link_to 'Destroy', ajaxtest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ajaxtest', new_ajaxtest_path %>

app/views/ajaxtests/new.html.erb
<h1>New Ajaxtest</h1>

<%= render 'form', ajaxtest: @ajaxtest %>

<%= link_to 'Back', ajaxtests_path %>

app/views/ajaxtests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ajaxtest.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @ajaxtest.mobile %>
</p>

<%= link_to 'Edit', edit_ajaxtest_path(@ajaxtest) %> |
<%= link_to 'Back', ajaxtests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajaxt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <%= render "shared/header"%>
    <%= yield %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="mt-5 bg-primary p-3">
	<div class="container">
     <div class="row">
     	<div class="col-lg-12">
     		<h1 class="text-white ">ajax demo</h1>
     </div>
	</div>

</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">ajax demo </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
         <%= link_to "users", ajaxtests_path,  class: "nav-link active " %>
        </li>
       
        </ul>
        
         
         
        
    </div>
  </div>
</nav>